name: Terraform Multi-Stage Pipeline (Single Branch)

on:
  push:
    branches:
      - main # or master
    paths:
      - 'environments/**'
      - '.github/workflows/terraform.yml'
      - 'modules/**'
      - 'variables.tf'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "us-east-1"
  TERRAFORM_VERSION: "1.7.0"

jobs:
  dev:
    name: Terraform Dev
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.commits[0].modified, 'environments/dev/') }}
    environment: development
    steps:
      - uses: ../../actions/composite/action.yml
  staging:
    name: Terraform Staging
    runs-on: ubuntu-latest
    needs: dev
    if: ${{ contains(github.event.commits[0].modified, 'environments/staging/') }}
    environment: staging
    steps:
      - uses: ../../actions/composite/action.yml
  prod:
    name: Terraform Prod
    runs-on: ubuntu-latest
    needs: staging
    if: ${{ contains(github.event.commits[0].modified, 'environments/prod/') }}
    environment: production
    steps:
      - uses: ../../actions/composite/action.yml